name: Linux Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: install-conan
        shell: bash
        run: |
          python --version
          sudo pip install conan

      - name: Set and Update conan profile
        shell: bash
        run: |
          echo build
          # mkdir build && cd build
          # sudo apt-get install libxcb-util-dev libxcb-util0-dev libudev-dev libgl-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev
          # conan install ${{ github.workspace }} -c tools.system.package_manager:mode=install
          # conan install ${{ github.workspace }} --build=missing

      - name: Build Test Linux
        shell: bash
        run: |
          mkdir build && cd build
          conan profile new default --detect
          export CONAN_SYSREQUIRES_MODE="enabled"
          export CONAN_SYSREQUIRES_SUDO="1"
          cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-11 ${{ github.workspace }}
          sudo apt-get upgrade python3
          sudo apt-get install libx11-xcb-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libudev-dev libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev libxcb-util-dev
          conan install ${{ github.workspace }} -c tools.system.package_manager:mode=install
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan install ${{ github.workspace }} --build missing
